name: Production Pipeline

on:
  push:
    paths:
      - 'automated-parent/docker-demo/src/**'
    branches: ["main"]
  workflow_dispatch:
  
jobs:
  code-pushing:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: build docker image
        run: |
          cd automated-parent
          docker build -t ghcr.io/shreshthtarwey/lpu-war2-image:1.0 -f docker-demo/Dockerfile .
      
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.LOGIN_TOKEN}}
      
      - name: Push To GHCR
        run: |
          docker push ghcr.io/shreshthtarwey/lpu-war2-image:1.0